// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type SupabaseClientType = import('@supabase/supabase-js').SupabaseClient<Database>;

let _client: SupabaseClientType | null = null;
let hasWarnedMissingConfig = false;

function warnMissingConfig() {
  if (hasWarnedMissingConfig || typeof window === 'undefined' || isSupabaseConfigured) return;
  hasWarnedMissingConfig = true;
  console.warn(
    'Supabase is not configured for this preview yet. Enable Lovable Cloud or provide VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to use auth and data features.',
  );
}

function createThenableResult(result: unknown) {
  let chain: any;
  chain = new Proxy(function noop() {}, {
    get(_target, prop) {
      if (prop === 'then') return Promise.resolve(result).then.bind(Promise.resolve(result));
      if (prop === 'catch') return Promise.resolve(result).catch.bind(Promise.resolve(result));
      if (prop === 'finally') return Promise.resolve(result).finally.bind(Promise.resolve(result));
      return chain;
    },
    apply() {
      return chain;
    },
  });

  return chain;
}

const authDisabledError = {
  message: 'Authentication is not configured yet.',
};

const fallbackQuery = createThenableResult({ data: null, error: null, count: 0 });

const fallbackClient = {
  auth: {
    onAuthStateChange: () => ({
      data: { subscription: { unsubscribe: () => {} } },
      error: null,
    }),
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    signOut: async () => ({ error: null }),
    signInWithPassword: async () => ({ data: { user: null, session: null }, error: authDisabledError }),
    signUp: async () => ({ data: { user: null, session: null }, error: authDisabledError }),
    resetPasswordForEmail: async () => ({ data: null, error: authDisabledError }),
    updateUser: async () => ({ data: { user: null }, error: authDisabledError }),
    setSession: async () => ({ data: { session: null, user: null }, error: authDisabledError }),
  },
  from: () => fallbackQuery,
  functions: new Proxy({}, {
    get() {
      return async () => ({ data: null, error: null });
    },
  }),
  channel: () => ({ on: () => ({ subscribe: () => ({}) }), subscribe: () => ({}) }),
  removeChannel: () => {},
} as unknown as SupabaseClientType;

async function initClient(): Promise<SupabaseClientType> {
  if (_client) return _client;
  if (!isSupabaseConfigured) {
    warnMissingConfig();
    return fallbackClient;
  }

  const { createClient } = await import('@supabase/supabase-js');
  _client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: typeof window !== 'undefined',
      autoRefreshToken: typeof window !== 'undefined',
      detectSessionInUrl: typeof window !== 'undefined',
    },
  });
  return _client;
}

function getClient(): SupabaseClientType {
  return _client ?? fallbackClient;
}

if (typeof window !== 'undefined') {
  void initClient();
}

export { initClient, getClient };

export const supabase = new Proxy(fallbackClient, {
  get(_target, prop) {
    if (_client) {
      return (_client as any)[prop];
    }

    if (typeof window !== 'undefined' && isSupabaseConfigured) {
      void initClient();
    } else {
      warnMissingConfig();
    }

    return (fallbackClient as any)[prop];
  },
});
